---
# mysql system set up
mysql_user: mysql
mysql_base_dir: /usr
mysql_data_dir: /var/lib/mysql
mysql_pid_file: /var/run/mariadb/mariadb.pid
mysql_log_file: /var/log/mariadb/mariadb.log
mysql_config_file: /etc/my.cnf
mysql_skip_name_resolve: no

# root username and password
mysql_root_username: root
mysql_root_password: root

# MySQL connection settings.
mysql_port: "3306"
mysql_bind_address: '0.0.0.0'

# data bases to be created
mysql_databases:
   - name: testDB
     collation: utf8_general_ci
     encoding: utf8

# Users.
mysql_users:
   - name: testUser
     host: '%'
     password: testPass
     priv: 'testDB.*:ALL'
   - name: testUser
     host: 'localhost'
     password: testPass
     priv: 'testDB.*:ALL'

# sloq query log
mysql_slow_query_log_enabled: no
mysql_slow_query_log_file: /var/log/mysql-slow.log
mysql_slow_query_time: "2"

# Memory settings (default values optimized ~512MB RAM).
mysql_key_buffer_size: "256M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_myisam_sort_buffer_size: "64M"
mysql_thread_cache_size: "8"
mysql_query_cache_type: "0"
mysql_query_cache_size: "16M"
mysql_query_cache_limit: "1M"
mysql_max_connections: "151"
mysql_tmp_table_size: "16M"
mysql_max_heap_table_size: "16M"
mysql_group_concat_max_len: "1024"
mysql_join_buffer_size: "262144"

# Other settings.
mysql_lower_case_table_names: "0"
mysql_wait_timeout: "28800"
mysql_event_scheduler_state: "OFF"

# InnoDB settings.
mysql_innodb_file_per_table: "1"
# Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
mysql_innodb_buffer_pool_size: "256M"
# Set .._log_file_size to 25% of buffer pool size.
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "1"
mysql_innodb_lock_wait_timeout: "50"
