---

- name: Install docker packages
  yum: name={{ item }} state=installed
  with_items:
    - docker
    - docker-compose
    - python-docker-py
    - PyYAML

- name: Start docker service
  service: name=docker state=started

